name       : pciutils
version    : 3.1.10
release    : 5
source     :
    - http://www.kernel.org/pub/software/utils/pciutils/pciutils-3.1.10.tar.gz : 5ee68fea2cb486632ef9b582975b05d5b185dba980467402427f5d6714221971
license    :
    - GPL-2.0
summary    : Utilities to deal with PCI bus
component  : system.utils
description: |
    The PCI Utilities are a collection of programs for inspecting and manipulating configuration of PCI devices, all based on a common portable library libpci which offers access to the PCI configuration space on a variety of operating systems.
build      : |
    %make PREFIX=/usr \
          OPT="$CFLAGS"\
          SHARED=yes \
          MANDIR=/usr/share/man \
          SHAREDIR=/usr/share/hwids \
          all

install    : |
    %make_install SHARED=yes \
                  PREFIX=/usr \
                  LIBDIR=/%libdir% \
                  INCDIR=/usr/include \
                  MANDIR=/usr/share/man \
                  SHAREDIR=/usr/share/hwids \
                  install-lib
    install -D -d -m 00755 $installdir/usr/bin
    mv $installdir/usr/sbin/lspci $installdir/usr/bin/.
