name       : pciutils
version    : 3.5.4
release    : 6
source     :
    - https://www.kernel.org/pub/software/utils/pciutils/pciutils-3.5.4.tar.xz : 64293c6ab9318c40ef262b76d87bd9097531759752bac556e50979b1e63cfe66
license    :
    - GPL-2.0
summary    : Utilities to deal with PCI bus
component  : system.utils
description: |
    The PCI Utilities are a collection of programs for inspecting and manipulating configuration of PCI devices, all based on a common portable library libpci which offers access to the PCI configuration space on a variety of operating systems.
setup      : |
    # In line with fedora
    %patch -p1 < $pkgfiles/idpath.patch
build      : |
    %make PREFIX=/usr \
          OPT="$CFLAGS"\
          SHARED=yes \
          MANDIR=/usr/share/man \
          IDSDIR=/usr/share/hwdata \
          PCI_IDS="pci.ids" \
          all

install    : |
    %make_install SHARED=yes \
                  PREFIX=/usr \
                  LIBDIR=/%libdir% \
                  INCDIR=/usr/include \
                  MANDIR=/usr/share/man \
                  IDSDIR=/usr/share/hwdata \
                  PCI_IDS="pci.ids" \
                  install-lib
    install -D -d -m 00755 $installdir/usr/bin
    mv $installdir/usr/sbin/lspci $installdir/usr/bin/.

    # This is handled by hwdata package
    rm -rf $installdir/usr/share/hwdata
