name       : pciutils
version    : 3.5.5
release    : 7
source     :
    - https://www.kernel.org/pub/software/utils/pciutils/pciutils-3.5.5.tar.xz : 1d62f8fa192f90e61c35a6fc15ff3cb9a7a792f782407acc42ef67817c5939f5
license    :
    - GPL-2.0
summary    : Utilities to deal with PCI bus
component  : system.utils
emul32     : yes
builddeps  :
    - pkgconfig32(libudev)
    - pkgconfig32(zlib)
description: |
    The PCI Utilities are a collection of programs for inspecting and manipulating configuration of PCI devices, all based on a common portable library libpci which offers access to the PCI configuration space on a variety of operating systems.
setup      : |
    # In line with fedora
    %patch -p1 < $pkgfiles/idpath.patch
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        export CC="$CC -m32"
    fi
    %make PREFIX=/usr \
          OPT="$CFLAGS"\
          SHARED=yes \
          MANDIR=/usr/share/man \
          IDSDIR=/usr/share/hwdata \
          PCI_IDS="pci.ids" \
          all \
          CC="$CC"

install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        export CC="$CC -m32"
    fi
    %make_install SHARED=yes \
                  PREFIX=/usr \
                  LIBDIR=/%libdir% \
                  INCDIR=/usr/include \
                  MANDIR=/usr/share/man \
                  IDSDIR=/usr/share/hwdata \
                  PCI_IDS="pci.ids" \
                  install-lib \
                  CC="$CC"
    install -D -d -m 00755 $installdir/usr/bin
    mv $installdir/usr/sbin/lspci $installdir/usr/bin/.

    # This is handled by hwdata package
    rm -rf $installdir/usr/share/hwdata
