name       : pciutils
version    : 3.6.2
release    : 9
source     :
    - https://mirrors.edge.kernel.org/pub/software/utils/pciutils/pciutils-3.6.2.tar.xz : db452ec986edefd88af0d222d22f6102f8030a8633fdfe846c3ae4bde9bb93f3
license    : GPL-2.0
component  : system.utils
emul32     : yes
summary    : Utilities to deal with PCI bus
description: |
    The PCI Utilities are a collection of programs for inspecting and manipulating configuration of PCI devices, all based on a common portable library libpci which offers access to the PCI configuration space on a variety of operating systems.
builddeps  :
    - pkgconfig32(libudev)
    - pkgconfig32(zlib)
setup      : |
    # In line with fedora
    %patch -p1 < $pkgfiles/idpath.patch
build      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        export CC="$CC -m32"
    fi
    %make PREFIX=/usr \
          OPT="$CFLAGS"\
          SHARED=yes \
          MANDIR=/usr/share/man \
          IDSDIR=/usr/share/hwdata \
          PCI_IDS="pci.ids" \
          all \
          CC="$CC"

install    : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        export CC="$CC -m32"
    fi
    %make_install SHARED=yes \
                  PREFIX=/usr \
                  LIBDIR=/%libdir% \
                  INCDIR=/usr/include \
                  MANDIR=/usr/share/man \
                  IDSDIR=/usr/share/hwdata \
                  PCI_IDS="pci.ids" \
                  install-lib \
                  CC="$CC"
    install -D -d -m 00755 $installdir/usr/bin
    mv $installdir/usr/sbin/lspci $installdir/usr/bin/.

    # This is handled by hwdata package
    rm -rf $installdir/usr/share/hwdata
